name: butterfliesar
description: "Aplicación Flutter multiplataforma (Android & iOS) para explorar mariposas en Realidad Aumentada."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.1
  # Plugins AR específicos por plataforma
  arkit_plugin: ^1.1.2 # Para iOS ARKit
  audioplayers: ^6.5.0
  webview_flutter: ^4.13.0 # Dependencia de model_viewer_plus
  vibration: ^3.1.3
  vector_math: ^2.1.4
  path: ^1.9.0
  camera: ^0.11.2
  model_viewer_plus: ^1.9.3 # Para modelos 3D como fallback
  lucide_icons_flutter: ^3.0.3
  url_launcher: ^6.3.2
  # Para verificación de soporte 3D/AR
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/favicon.png
    - assets/images/
    - assets/models/
    - assets/sounds/
    - assets/backgrounds/
    - lib/data/butterflies.json
